
package br.com.rukaso.estoquews.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "EstoqueWS", targetNamespace = "http://ws.estoque.caelum.com.br/", wsdlLocation = "http://localhost:8080/EstoqueWS-Web/EstoqueWS/EstoqueWSImpl?wsdl")
public class EstoqueWS_Service
    extends Service
{

    private final static URL ESTOQUEWS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(br.com.rukaso.estoquews.cliente.EstoqueWS_Service.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = br.com.rukaso.estoquews.cliente.EstoqueWS_Service.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/EstoqueWS-Web/EstoqueWS/EstoqueWSImpl?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/EstoqueWS-Web/EstoqueWS/EstoqueWSImpl?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ESTOQUEWS_WSDL_LOCATION = url;
    }

    public EstoqueWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstoqueWS_Service() {
        super(ESTOQUEWS_WSDL_LOCATION, new QName("http://ws.estoque.caelum.com.br/", "EstoqueWS"));
    }

    /**
     * 
     * @return
     *     returns EstoqueWS
     */
    @WebEndpoint(name = "EstoqueWSImplPort")
    public EstoqueWS getEstoqueWSImplPort() {
        return super.getPort(new QName("http://ws.estoque.caelum.com.br/", "EstoqueWSImplPort"), EstoqueWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstoqueWS
     */
    @WebEndpoint(name = "EstoqueWSImplPort")
    public EstoqueWS getEstoqueWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.estoque.caelum.com.br/", "EstoqueWSImplPort"), EstoqueWS.class, features);
    }

}
